### PR TITLE
don't write to full buffers

### PR DESCRIPTION
**Pull request by jankolkmeier**
Does this help #33 ?

### CODE REVIEW

**Comment by emnik** [comment]
Indeed It kind of solves the problem. I added a 
```
console.log('S.buffer.length='+S.buffer.length, 'S.offset='+S.offset);
```
just before the new if...
You can see the result at http://pastebin.com/FMnddGcW
At first It doesn't emit a "frame_raw" signal until it logs "We would have a problem..."
Then it starts working right! without a RangeError!
The only downside is that it takes about 10 minutes to get it to work right. (I am sending data via RF about every minute)

**Comment by jankolkmeier** [comment]
Hmm, sorry it doesn't fix it better. Did it also take 10 minutes for the crash to appear previously?

**Comment by jankolkmeier** [comment]
Can you try with this last commit? I'm surprised it passed the checks, and I am hesitant to make this upstream before giving it a closer look... but that check I removed may have been needless, and may have been keeping the parser from missing actual data in your case...

**Comment by emnik** [comment]
Ok, yes the error did take ~ 10 minutes for the crash at start.
Your last commit though, seems to solve the problem completely without any delay !!!

**Comment by jankolkmeier** [comment]
Glad it works! Please keep an eye on it, see if it breaks anything else!

**Comment by emnik** [comment]
Of course, I'll keep you informed!
Thank you very much for your help and your time!

**Pull request merged**
